blank_issues_enabled: true
contact_links:
  - name: Contributing guide
    url: https://github.com/quackcom/openkernel/blob/main/CONTRIBUTING.md
    about: How to contribute respectfully and effectively
